// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GibbsSampling")>]
[<assembly: AssemblyProductAttribute("GibbsSampling")>]
[<assembly: AssemblyDescriptionAttribute("Algorithm for motif finding.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GibbsSampling"
    let [<Literal>] AssemblyProduct = "GibbsSampling"
    let [<Literal>] AssemblyDescription = "Algorithm for motif finding."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
